version: "3.9"
services:

  mongo:
    image: mongo:latest
    container_name: mongo_replica_set
    restart: always
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
      - ./init-replica-set.sh:/docker-entrypoint-initdb.d/init-replica-set.sh
