version: "3.9"
services:

  mongo:
    image: mongo:7.0.5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
