name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Test End-to-End
        run: npm test:e2e

      - name: Build Image
        run: npm run docker:build

      - name: Push Image
        run: npm run docker:push

